package easy

// You are given two strings s and t.
//
// String t is generated by random shuffling string s and then add one more letter at a random position.
//
// Return the letter that was added to t.
//
//
//
// Example 1:
// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
//
// Example 2:
// Input: s = "", t = "y"
// Output: "y"
//
// Example 3:
// Input: s = "a", t = "aa"
// Output: "a"
//
// Example 4:
// Input: s = "ae", t = "aea"
// Output: "a"
func findTheDifference(s string, t string) byte {
	if len(s) == 0 {
		return t[0]
	}
	if len(t) == 0 {
		return s[0]
	}

	var res uint8
	for i, j := 0, 0; i < len(s); i, j = i+1, j+1 {
		res ^= s[i] ^ t[j]
	}

	return res ^ t[len(t)-1]
}
